language: ruby
sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update
- sudo apt-get -y install python3-pip texlive-full
- sudo pip3 install --upgrade pip
- sudo pip3 install sphinx
- sudo pip3 install sphinx_bootstrap_theme
env:
  matrix:
  - COMMAND="make clean html latexpdf epub"
before_deploy: mv build/latex/KubuntuManual.pdf build/latex/KubuntuManual-18.04.pdf
  && mv build/epub/KubuntuManual.epub build/epub/KubuntuManual-18.04.epub
deploy:
  provider: releases
  user: ahoneybun
  password:
    secure: Gr+piCnltxqMO0gKO0WUHc6N90avCQI/jmdEZM5uHHonFsQa1rupI2PIu+mLUjqdFfKKItUkchQIfixR1kwjoZW8OCJwjtg+nhb8ZWCIQsykTZ7JcdvMTPdDW5oW8zrkzv0V1Nk9OGEvjqptKSWIxzos2bH2ba/pxeNBGk3G8/N2dwjJtl5RfQ6arm0b1KMgPiBpzq7fGbLJosqXLmG5Qa4MKFuJA4x58Ik23QGh6DiBPcJPoDp83vsQp42BzOxY623cHjDy/hhW5wsjLhT7d8GY8oA+qRshqqRp2rzEMdFEtNpsjC0/n1oPDz5qGD7mQG6jcsE/lQ4+6lZgV5W0WKhGf56zAsCkaSsRmNGlmOWkyBCJ4WXVdi0zbWjkeg01Mz8rkBsp0+hD2tj8rdoej6MOY1b1SPdGYeDZ+EUqfCV5aikbODH/oeBbmPOJ6xY2/C6Io3FJHflTxRUUOmBqycfwsmdjg4krVEQ8Bh7/ALHVXF+dj+iwt+N9bhwvNjGamXEafgYc5xJ1CcKV6yPTpcxtYG536EpntQK0Muf2mYfi1pfWLy2UOKOba/GyQ7YMQoup3bvDUe7MnsmIYL1ATVaiOGFoTD3i3lh1qa7eudI4/wRZ1LZRFe8Ld1tEKSQ5f4Y/IN2nvZEpd/SgybWvZ7/CEAPfaOd9HIVEhfGJ/Uo=
  file:
  - build/epub/KubuntuManual-18.04.epub
  - build/latex/KubuntuManual-18.04.pdf
  skip_cleanup: true
  on:
    tags: true
    branch: kubuntu-18.04-LTS
notifications:
  email:
  - aaronhoneycutt@kubuntu.org
  slack: kubuntu:puzVpRNriVEjjGOmGqvws9FU
script:
- bash -c "$COMMAND"
